### ISSUE TITLE
Update all ssh keys to follow scheme

### ISSUE THREAD

**Issue by butlerx** [redbrick/nix-configs#35]
All ssh key should follow the standard as follows 
- `ssh-ed25519` required 
- usernames should be rb ones eg `<username>@redbrick.dcu.ie` 

so for example
 ```
ssh-ed25519 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx <usernam>@redbrick.dcu.ie
```

**Comment by theycallmemac** [comment]
Closed by https://github.com/redbrick/nix-configs/commit/9e3592f3cfb704ba4b0c2f82f194663dd766cb5d

**Comment by butlerx** [comment]
@theycallmemac not all the keys in the file are following the scheme
