### ISSUE TITLE
Create reserved user + configure gitea email

### ISSUE THREAD

**Issue by m1cr0man** [redbrick/nix-configs#63]
Gitea cannot send email at the moment due to the new security requirements of the new stack.

- Create an LDAP user under ou=reserved,o=redbrick with class posixAccount (look at cloning mailmgr)
- Configure Gitea to use these credentials to log into the mail server at address `localmail.redbrick.dcu.ie:587`

**Comment by butlerx** [comment]
@m1cr0man was this done in #67?

**Comment by m1cr0man** [comment]
Yes actually. The reserved user is called rbgit, to avoid conflicts with the nixos gitea user. And I tested mail sending too.
